export interface CurtainTool { id: number; name: string; slug: string; description: string; icon: string; }
export const curtainTools: CurtainTool[] = [
    { id: 238, name: "Curtain Yardage Calculator", slug: "yardage-calculator", description: "Complete curtain fabric calculator", icon: "🪟" },
    { id: 239, name: "Curtain Fullness Ratio", slug: "fullness-calculator", description: "Fabric width for different fullness levels", icon: "" },
    { id: 240, name: "Panel Width Calculator", slug: "panel-width", description: "Individual panel width calculation", icon: "" },
    { id: 241, name: "Curtain Length Calculator", slug: "length-calculator", description: "Length for sill, floor, and puddle", icon: "" },
    { id: 242, name: "Header Calculator", slug: "header-calculator", description: "Fabric for different header styles", icon: "" },
    { id: 243, name: "Rod Pocket Size Calculator", slug: "rod-pocket", description: "Rod pocket casing width", icon: "" },
    { id: 244, name: "Lining Yardage Calculator", slug: "lining-calculator", description: "Lining fabric for curtains", icon: "" },
    { id: 245, name: "Interlining Calculator", slug: "interlining", description: "Interlining for lined curtains", icon: "" },
    { id: 246, name: "Valance Yardage Calculator", slug: "valance-calculator", description: "Yardage for valances by style", icon: "" },
    { id: 247, name: "Pelmet/Cornice Calculator", slug: "pelmet-calculator", description: "Fabric for pelmets and cornices", icon: "" },
    { id: 248, name: "Roman Blind Calculator", slug: "roman-blind", description: "Fabric for Roman shades", icon: "" },
    { id: 249, name: "Roman Blind Ring Spacing", slug: "roman-blind-rings", description: "Ring spacing for even folds", icon: "⭕" },
    { id: 250, name: "Roller Blind Calculator", slug: "roller-blind", description: "Fabric for roller blinds", icon: "" },
    { id: 251, name: "Cafe Curtain Calculator", slug: "cafe-curtain", description: "Yardage for cafe curtains", icon: "" },
    { id: 252, name: "Swag and Tail Calculator", slug: "swag-tail", description: "Fabric for swag and tail treatments", icon: "" },
    { id: 253, name: "Blackout Curtain Calculator", slug: "blackout", description: "Yardage for blackout curtains", icon: "" },
    { id: 254, name: "Window Measurement Guide", slug: "measurement-guide", description: "How to measure windows", icon: "" },
];
