export interface GarmentTool { id: number; name: string; slug: string; description: string; icon: string; }
export const garmentTools: GarmentTool[] = [
    { id: 201, name: "Dart Calculator", slug: "dart-calculator", description: "Calculate dart width, length, and intake", icon: "" },
    { id: 202, name: "Dart Intake Calculator", slug: "dart-intake", description: "How much fabric a dart takes in", icon: "" },
    { id: 203, name: "Dart Rotation Tool", slug: "dart-rotation", description: "Guide for rotating darts to different positions", icon: "" },
    { id: 204, name: "Dart Equivalents", slug: "dart-equivalents", description: "Convert dart intake to gathers, tucks, or ease", icon: "" },
    { id: 205, name: "Pleat Calculator", slug: "pleat-calculator", description: "Calculate pleat depth, spacing, and number", icon: "" },
    { id: 206, name: "Pleat Spacing Tool", slug: "pleat-spacing", description: "Even pleat spacing for any width", icon: "" },
    { id: 207, name: "Gather Ratio Calculator", slug: "gather-ratio", description: "Fabric needed for gathering by fullness ratio", icon: "" },
    { id: 208, name: "Ruffle Fullness Calculator", slug: "ruffle-calculator", description: "Fabric strip length for ruffles", icon: "" },
    { id: 209, name: "Smocking Yardage", slug: "smocking-calculator", description: "Fabric width for smocking", icon: "" },
    { id: 210, name: "Hem Allowance Calculator", slug: "hem-allowance", description: "Hem allowance by hem type", icon: "" },
    { id: 211, name: "Hem Depth Comparator", slug: "hem-depth-comparator", description: "Compare hem depths and visual effect", icon: "" },
    { id: 212, name: "Curved Hem Calculator", slug: "curved-hem", description: "Adjustments for hemming curved edges", icon: "" },
    { id: 213, name: "Rolled Hem Calculator", slug: "rolled-hem", description: "Settings for machine or hand-rolled hems", icon: "" },
    { id: 214, name: "Blind Hem Calculator", slug: "blind-hem", description: "Fold depths for invisible blind hems", icon: "" },
    { id: 215, name: "Horsehair Braid Hem", slug: "horsehair-hem", description: "Horsehair braid length for structured hems", icon: "" },
    { id: 216, name: "Waistband Calculator", slug: "waistband-calculator", description: "Waistband length and width calculation", icon: "" },
    { id: 217, name: "Waistband Interfacing", slug: "waistband-interfacing", description: "Interfacing dimensions for waistbands", icon: "" },
    { id: 218, name: "Fly Zipper Calculator", slug: "fly-zipper", description: "Fly zipper length from body measurements", icon: "" },
    { id: 219, name: "Placket Calculator", slug: "placket-calculator", description: "Placket dimensions for various types", icon: "" },
    { id: 220, name: "Collar Stand Calculator", slug: "collar-stand", description: "Collar stand dimensions by collar type", icon: "" },
    { id: 221, name: "Sleeve Length Adjustment", slug: "sleeve-length", description: "Sleeve length from arm measurements", icon: "" },
    { id: 222, name: "Cuff Size Calculator", slug: "cuff-calculator", description: "Cuff dimensions for various styles", icon: "" },
    { id: 223, name: "Sleeve Cap Ease", slug: "sleeve-cap-ease", description: "Sleeve cap ease calculation", icon: "" },
    { id: 224, name: "Sleeve Style Converter", slug: "sleeve-style-converter", description: "Convert between set-in and raglan sleeves", icon: "" },
    { id: 225, name: "Pocket Placement Tool", slug: "pocket-placement", description: "Pocket placement positions", icon: "" },
    { id: 226, name: "Inseam vs Outseam", slug: "inseam-outseam", description: "Convert between inseam and outseam", icon: "" },
    { id: 227, name: "Ease by Style Guide", slug: "ease-by-style", description: "Standard ease by garment style", icon: "" },
    { id: 228, name: "Fabric Grain Line Guide", slug: "grain-line-guide", description: "Guide for straight grain, cross grain, bias", icon: "" },
];
