export interface HomeDecorTool { id: number; name: string; slug: string; description: string; icon: string; }
export const homeDecorTools: HomeDecorTool[] = [
    { id: 255, name: "Sofa Upholstery Yardage", slug: "sofa-upholstery", description: "Yardage for reupholstering sofas", icon: "🛋️" },
    { id: 256, name: "Armchair Upholstery", slug: "armchair-upholstery", description: "Yardage for armchairs", icon: "💺" },
    { id: 257, name: "Dining Chair Upholstery", slug: "dining-chair-upholstery", description: "Yardage for dining chairs", icon: "🪑" },
    { id: 258, name: "Ottoman Upholstery", slug: "ottoman-upholstery", description: "Yardage for ottomans", icon: "🟫" },
    { id: 259, name: "Bench Upholstery", slug: "bench-upholstery", description: "Yardage for benches", icon: "🪵" },
    { id: 260, name: "Headboard Upholstery", slug: "headboard-upholstery", description: "Fabric for upholstered headboards", icon: "🛏️" },
    { id: 261, name: "Cushion Cover (Zipper)", slug: "cushion-cover-zipper", description: "Fabric for zipper cushion covers", icon: "🔲" },
    { id: 262, name: "Cushion Cover (Envelope)", slug: "cushion-cover-envelope", description: "Fabric for envelope-back covers", icon: "✉️" },
    { id: 263, name: "Pillow Insert Size Guide", slug: "pillow-insert-guide", description: "Insert size for any cover", icon: "📏" },
    { id: 264, name: "Bolster Pillow Calculator", slug: "bolster-calculator", description: "Fabric for bolster pillows", icon: "🔵" },
    { id: 265, name: "Box Cushion Calculator", slug: "box-cushion", description: "Fabric for box-style cushions", icon: "📦" },
    { id: 266, name: "Round Cushion Calculator", slug: "round-cushion", description: "Fabric for round cushions", icon: "⭕" },
    { id: 267, name: "Floor Cushion/Pouf", slug: "floor-cushion", description: "Fabric for floor cushions", icon: "🟤" },
    { id: 268, name: "Piping/Welt Cord Yardage", slug: "piping-calculator", description: "Bias strip and cord for piping", icon: "〰️" },
    { id: 269, name: "Tablecloth Calculator", slug: "tablecloth-calculator", description: "Tablecloth dimensions", icon: "🍽️" },
    { id: 270, name: "Table Runner Calculator", slug: "table-runner", description: "Fabric for table runners", icon: "🏃" },
    { id: 271, name: "Placemat Calculator", slug: "placemat-calculator", description: "Fabric for placemats", icon: "🍴" },
    { id: 272, name: "Napkin Yardage Calculator", slug: "napkin-calculator", description: "Yardage for cloth napkins", icon: "🧻" },
    { id: 273, name: "Table Topper Calculator", slug: "table-topper", description: "Fabric for table toppers", icon: "🔷" },
    { id: 274, name: "Duvet Cover Calculator", slug: "duvet-cover", description: "Fabric for duvet covers", icon: "🛏️" },
    { id: 275, name: "Bed Skirt Calculator", slug: "bed-skirt", description: "Yardage for bed skirts", icon: "👗" },
    { id: 276, name: "Fitted Sheet Calculator", slug: "fitted-sheet", description: "Fabric for fitted sheets", icon: "📐" },
    { id: 277, name: "Flat Sheet Calculator", slug: "flat-sheet", description: "Fabric for flat sheets", icon: "📏" },
    { id: 278, name: "Pillow Sham Calculator", slug: "pillow-sham", description: "Fabric for pillow shams", icon: "🛌" },
    { id: 279, name: "Bed Size Reference", slug: "bed-sizes", description: "Mattress dimensions reference", icon: "📖" },
];
