export interface NotionTool { id: number; name: string; slug: string; description: string; icon: string; }
export const notionTools: NotionTool[] = [
    { id: 180, name: "Thread Yardage Estimator", slug: "thread-yardage", description: "Estimate thread needed based on seam length and type", icon: "🧵" },
    { id: 181, name: "Bobbin Thread Calculator", slug: "bobbin-thread", description: "Calculate bobbins needed for a project", icon: "🔄" },
    { id: 182, name: "Thread Weight Comparison", slug: "thread-weight-comparison", description: "Compare thread weights with recommendations", icon: "⚖️" },
    { id: 183, name: "Thread Color Matching", slug: "thread-color-matching", description: "Guide for choosing thread color", icon: "🎨" },
    { id: 184, name: "Thread Type by Fabric", slug: "thread-by-fabric", description: "Match thread types to fabric types", icon: "📋" },
    { id: 185, name: "Spool Size Comparison", slug: "spool-size-comparison", description: "Compare spool sizes and economy", icon: "📊" },
    { id: 186, name: "Button Size Calculator", slug: "button-size-calculator", description: "Convert button sizes: ligne, mm, inches", icon: "🔘" },
    { id: 187, name: "Button Spacing Calculator", slug: "button-spacing", description: "Calculate even button spacing", icon: "📏" },
    { id: 188, name: "Buttonhole Length Calculator", slug: "buttonhole-calculator", description: "Buttonhole length from button diameter", icon: "🕳️" },
    { id: 189, name: "Zipper Length Selector", slug: "zipper-length", description: "Correct zipper length by garment type", icon: "🤐" },
    { id: 190, name: "Hook & Eye Spacing", slug: "hook-eye-spacing", description: "Even spacing for hooks and eyes", icon: "🪝" },
    { id: 191, name: "Snap Spacing Calculator", slug: "snap-spacing", description: "Even spacing for snaps", icon: "⚡" },
    { id: 192, name: "Elastic Calculator", slug: "elastic-calculator", description: "Elastic length and width by application", icon: "〰️" },
    { id: 193, name: "Ribbon Length Calculator", slug: "ribbon-calculator", description: "Ribbon needed for projects", icon: "🎀" },
    { id: 194, name: "Lace Yardage Calculator", slug: "lace-calculator", description: "Lace yardage for various applications", icon: "🌸" },
    { id: 195, name: "Trim Yardage Calculator", slug: "trim-calculator", description: "Yardage for any trim type", icon: "✨" },
    { id: 196, name: "Interfacing Calculator", slug: "interfacing-calculator", description: "Select interfacing type and calculate yardage", icon: "📐" },
    { id: 197, name: "Stabilizer Calculator", slug: "stabilizer-calculator", description: "Stabilizer for embroidery and applique", icon: "🧩" },
    { id: 198, name: "Fusible Web Calculator", slug: "fusible-web-calculator", description: "Fusible web yardage for applique", icon: "🔥" },
    { id: 199, name: "Elastic Casing Width", slug: "casing-width", description: "Casing width from elastic width", icon: "📏" },
    { id: 200, name: "Boning Calculator", slug: "boning-calculator", description: "Boning lengths for corsets and bodices", icon: "🦴" },
];
