export interface QuiltTool { id: number; name: string; slug: string; description: string; icon: string; }
export const quiltTools: QuiltTool[] = [
    { id: 129, name: "Quilt Size Calculator", slug: "size-calculator", description: "Calculate finished quilt size from blocks, sashing, and borders", icon: "📐" },
    { id: 130, name: "Blocks Needed Calculator", slug: "blocks-needed", description: "How many blocks for a specific quilt size", icon: "🔢" },
    { id: 131, name: "Quilt Layout Planner", slug: "layout-planner", description: "Visual grid planner for block arrangement", icon: "🗂️" },
    { id: 132, name: "Block Size Calculator", slug: "block-size-calculator", description: "Finished and unfinished block sizes with SA", icon: "🟩" },
    { id: 133, name: "Standard Quilt Sizes", slug: "standard-sizes", description: "Reference for all standard quilt sizes", icon: "📖" },
    { id: 134, name: "Virtual Design Wall", slug: "design-wall", description: "Visual design wall for block arrangement", icon: "🎨" },
    { id: 135, name: "Color Proportion Tool", slug: "color-proportion", description: "Calculate and visualize fabric color proportions", icon: "🌈" },
    { id: 136, name: "Backing Yardage Calculator", slug: "backing-calculator", description: "Backing yardage with seam placement options", icon: "🟫" },
    { id: 137, name: "Batting Size Calculator", slug: "batting-calculator", description: "Determine batting size needed", icon: "☁️" },
    { id: 138, name: "Binding Calculator", slug: "binding-calculator", description: "Binding strip length, count, and yardage", icon: "🎀" },
    { id: 139, name: "Binding Strip Width", slug: "binding-strip-width", description: "Cut strip width for desired finished binding", icon: "📏" },
    { id: 140, name: "Binding Strip Length", slug: "binding-strip-length", description: "Total binding length with allowances", icon: "📐" },
    { id: 141, name: "Binding Yardage", slug: "binding-yardage", description: "Yardage from strip count and fabric width", icon: "🧵" },
    { id: 142, name: "Sashing Calculator", slug: "sashing-calculator", description: "Sashing dimensions and yardage", icon: "➕" },
    { id: 143, name: "Border Calculator", slug: "border-calculator", description: "Border dimensions and yardage", icon: "🖼️" },
    { id: 144, name: "Setting Triangles", slug: "setting-triangles", description: "Side and corner triangle dimensions for on-point quilts", icon: "🔺" },
    { id: 145, name: "Cornerstone Calculator", slug: "cornerstone-calculator", description: "Cornerstone sizes and quantities for sashing", icon: "⬛" },
    { id: 146, name: "HST Calculator", slug: "hst-calculator", description: "Half-square triangle cutting sizes", icon: "◣" },
    { id: 147, name: "HST Yield Calculator", slug: "hst-yield", description: "How many HSTs from a given square size", icon: "📊" },
    { id: 148, name: "QST Calculator", slug: "qst-calculator", description: "Quarter-square triangle cutting sizes", icon: "◢" },
    { id: 149, name: "Flying Geese Calculator", slug: "flying-geese-calculator", description: "Cutting sizes for flying geese units", icon: "🦆" },
    { id: 150, name: "Snowball Block Calculator", slug: "snowball-calculator", description: "Corner square sizes for snowball blocks", icon: "⚪" },
    { id: 151, name: "Nine-Patch Calculator", slug: "nine-patch-calculator", description: "Strip widths for nine-patch blocks", icon: "#️⃣" },
    { id: 152, name: "Log Cabin Calculator", slug: "log-cabin-calculator", description: "Strip widths for log cabin blocks", icon: "🏠" },
    { id: 153, name: "Dresden Plate Calculator", slug: "dresden-plate-calculator", description: "Blade sizes and angles for Dresden plates", icon: "🌸" },
    { id: 154, name: "Hexagon Calculator (EPP)", slug: "hexagon-calculator", description: "Hexagon dimensions for English Paper Piecing", icon: "⬡" },
    { id: 155, name: "Star Block Calculator", slug: "star-block-calculator", description: "Cutting dimensions for star blocks", icon: "⭐" },
    { id: 156, name: "Pinwheel Calculator", slug: "pinwheel-calculator", description: "Cutting sizes for pinwheel blocks", icon: "🌀" },
    { id: 157, name: "Irish Chain Calculator", slug: "irish-chain-calculator", description: "Cutting and yardage for Irish Chain quilts", icon: "🍀" },
    { id: 158, name: "FPP Size Calculator", slug: "fpp-calculator", description: "Template and fabric sizes for foundation paper piecing", icon: "📄" },
    { id: 159, name: "Kaleidoscope Calculator", slug: "kaleidoscope-calculator", description: "Cutting sizes for kaleidoscope blocks", icon: "🔮" },
    { id: 160, name: "Charm Pack Calculator", slug: "charm-pack-calculator", description: "Projects from charm packs (42 × 5\" squares)", icon: "✨" },
    { id: 161, name: "Jelly Roll Calculator", slug: "jelly-roll-calculator", description: "Projects from jelly rolls (40 × 2.5\" strips)", icon: "🌀" },
    { id: 162, name: "Layer Cake Calculator", slug: "layer-cake-calculator", description: "Projects from layer cakes (42 × 10\" squares)", icon: "🎂" },
    { id: 163, name: "Fat Quarter Bundle Calculator", slug: "fat-quarter-bundle-calculator", description: "Projects from fat quarter bundles", icon: "📦" },
    { id: 164, name: "Scrappy Quilt Estimator", slug: "scrappy-yardage", description: "Yardage for scrappy quilts from mixed scraps", icon: "🧩" },
    { id: 165, name: "Mini Charm Calculator", slug: "mini-charm-calculator", description: "Projects from mini charm packs (2.5\" squares)", icon: "💎" },
    { id: 166, name: "Turnover Calculator", slug: "turnover-calculator", description: "Projects from pre-cut triangle packs", icon: "🔺" },
];
