export interface SkirtTool { id: number; name: string; slug: string; description: string; icon: string; }
export const skirtTools: SkirtTool[] = [
    { id: 351, name: "Full Circle Skirt", slug: "full-circle", description: "Waist radius, hem, and yardage", icon: "⭕" },
    { id: 352, name: "Half Circle Skirt", slug: "half-circle", description: "180° skirt dimensions", icon: "🌓" },
    { id: 353, name: "Quarter Circle Skirt", slug: "quarter-circle", description: "90° gentle flare skirt", icon: "🌘" },
    { id: 354, name: "Three-Quarter Circle", slug: "three-quarter-circle", description: "270° skirt dimensions", icon: "🌔" },
    { id: 355, name: "Custom Angle Circle", slug: "custom-angle-circle", description: "Any angle circle skirt", icon: "📐" },
    { id: 356, name: "A-Line Skirt", slug: "a-line", description: "A-line dimensions and flare", icon: "🔺" },
    { id: 357, name: "Flared Skirt", slug: "flared", description: "Variable flare amounts", icon: "📊" },
    { id: 358, name: "Waist Radius Calculator", slug: "waist-radius", description: "Radius from waist measurement", icon: "📏" },
    { id: 359, name: "Hem Circumference", slug: "hem-circumference", description: "Hem size for circle skirts", icon: "〰️" },
    { id: 360, name: "Skirt Yardage by Style", slug: "yardage-by-style", description: "Compare all skirt styles", icon: "📋" },
    { id: 361, name: "Pleated Skirt", slug: "pleated", description: "Knife, box, and accordion pleats", icon: "📄" },
    { id: 362, name: "Tiered Skirt", slug: "tiered", description: "Multi-tier prairie skirts", icon: "🎂" },
    { id: 363, name: "Length Comparator", slug: "length-comparator", description: "Maxi vs midi vs mini", icon: "📐" },
    { id: 364, name: "Wrap Skirt", slug: "wrap-skirt", description: "Wrap skirt with overlap", icon: "🔄" },
    { id: 365, name: "Tulip/Petal Skirt", slug: "tulip-skirt", description: "Tulip overlap pattern", icon: "🌷" },
    { id: 366, name: "High-Low Hem Skirt", slug: "high-low", description: "Asymmetric hem skirt", icon: "↗️" },
];
export interface BagTool { id: number; name: string; slug: string; description: string; icon: string; }
export const bagTools: BagTool[] = [
    { id: 367, name: "Tote Bag Calculator", slug: "tote-calculator", description: "Fabric for tote bags", icon: "👜" },
    { id: 368, name: "Bag Lining Calculator", slug: "lining-calculator", description: "Lining for any bag", icon: "🔲" },
    { id: 369, name: "Bag Interfacing", slug: "interfacing-calculator", description: "Interfacing for structured bags", icon: "📋" },
    { id: 370, name: "Strap Length Calculator", slug: "strap-length", description: "Strap for shoulder, crossbody", icon: "📏" },
    { id: 371, name: "Strap Width Calculator", slug: "strap-width", description: "Cutting width for straps", icon: "📐" },
    { id: 372, name: "Zipper Pouch", slug: "zipper-pouch", description: "Lined zippered pouches", icon: "🔒" },
    { id: 373, name: "Wallet Calculator", slug: "wallet-calculator", description: "Fabric wallet dimensions", icon: "👛" },
    { id: 374, name: "Backpack Calculator", slug: "backpack-calculator", description: "Backpack panel dimensions", icon: "🎒" },
    { id: 375, name: "Drawstring Bag", slug: "drawstring", description: "Drawstring bags/pouches", icon: "🪢" },
    { id: 376, name: "Market/Grocery Bag", slug: "market-bag", description: "Reusable grocery bags", icon: "🛒" },
    { id: 377, name: "Gift Bag", slug: "gift-bag", description: "Fabric gift bags", icon: "🎁" },
    { id: 378, name: "Clutch/Evening Bag", slug: "clutch", description: "Clutch purse dimensions", icon: "👝" },
    { id: 379, name: "Messenger Bag", slug: "messenger", description: "Messenger bag panels", icon: "💼" },
    { id: 380, name: "Laptop Sleeve", slug: "laptop-sleeve", description: "Padded laptop sleeves", icon: "💻" },
    { id: 381, name: "Hat Size Calculator", slug: "hat-calculator", description: "Fabric for hats", icon: "🧢" },
    { id: 382, name: "Headband Calculator", slug: "headband-calculator", description: "Headband width and length", icon: "🤸" },
    { id: 383, name: "Scrunchie Calculator", slug: "scrunchie", description: "Fabric for scrunchies", icon: "💫" },
    { id: 384, name: "Face Mask Calculator", slug: "face-mask", description: "Pleated/fitted masks", icon: "😷" },
    { id: 385, name: "Fabric Basket", slug: "fabric-basket", description: "Storage basket dimensions", icon: "🧺" },
];
