export interface SustainableTool { id: number; name: string; slug: string; description: string; icon: string; }
export const sustainableTools: SustainableTool[] = [
    { id: 450, name: "Waste Percentage Calculator", slug: "waste-percentage", description: "Calculate fabric waste %", icon: "" },
    { id: 451, name: "Zero-Waste Cutting Guide", slug: "zero-waste-cutting", description: "Zero-waste techniques", icon: "" },
    { id: 452, name: "Remnant Usage Calculator", slug: "remnant-usage", description: "Projects from leftover fabric", icon: "" },
    { id: 453, name: "Fabric Stash Tracker", slug: "stash-tracker", description: "Track your fabric stash", icon: "" },
    { id: 454, name: "Eco-Fabric Comparator", slug: "eco-fabric", description: "Compare eco-friendly fabrics", icon: "" },
    { id: 455, name: "Sustainable Fiber Guide", slug: "fiber-guide", description: "Guide to sustainable fibers", icon: "" },
    { id: 456, name: "Upcycling Calculator", slug: "upcycling", description: "New items from old garments", icon: "" },
    { id: 457, name: "Carbon Footprint Compare", slug: "carbon-footprint", description: "Handmade vs store-bought", icon: "" },
    { id: 458, name: "Donation Value Calculator", slug: "donation-value", description: "Value fabric for swaps", icon: "" },
    { id: 459, name: "Scrap Sorting Guide", slug: "scrap-sorting", description: "Sort scraps by usable size", icon: "" },
    { id: 460, name: "Make vs Buy Calculator", slug: "make-vs-buy", description: "Environmental impact compare", icon: "" },
];
export interface ReferenceTool { id: number; name: string; slug: string; description: string; icon: string; }
export const referenceTools: ReferenceTool[] = [
    { id: 461, name: "Sewing Glossary", slug: "glossary", description: "A-Z sewing terms", icon: "" },
    { id: 462, name: "Fabric Encyclopedia", slug: "fabric-encyclopedia", description: "Fabric types A-Z", icon: "" },
    { id: 463, name: "Stitch Database", slug: "stitch-database", description: "Stitch types and settings", icon: "" },
    { id: 464, name: "Pattern Symbol Guide", slug: "pattern-symbols", description: "Pattern markings guide", icon: "" },
    { id: 465, name: "Abbreviations Database", slug: "abbreviations", description: "Sewing abbreviations", icon: "" },
    { id: 466, name: "Conversion Quick Reference", slug: "conversion-quick-ref", description: "All-in-one conversions", icon: "" },
    { id: 467, name: "Seam Allowance Chart", slug: "seam-allowance-chart", description: "Standard seam allowances", icon: "" },
    { id: 468, name: "Quilt Size Chart", slug: "quilt-size-chart", description: "Standard quilt sizes", icon: "" },
    { id: 469, name: "Clothing Size Charts", slug: "clothing-size-charts", description: "US/UK/EU sizing", icon: "" },
    { id: 470, name: "Bed/Mattress Size Chart", slug: "bed-size-chart", description: "Mattress sizes worldwide", icon: "" },
    { id: 471, name: "Window Size Reference", slug: "window-sizes", description: "Standard window dimensions", icon: "🪟" },
    { id: 472, name: "Table Size Reference", slug: "table-sizes", description: "Standard table dimensions", icon: "" },
    { id: 473, name: "Pillow Size Reference", slug: "pillow-sizes", description: "Standard pillow sizes", icon: "" },
    { id: 474, name: "Beginner Checklist", slug: "beginner-checklist", description: "Essential sewing supplies", icon: "" },
    { id: 475, name: "Skill Assessment", slug: "skill-assessment", description: "Test your skill level", icon: "" },
    { id: 476, name: "Project Difficulty Guide", slug: "project-difficulty", description: "Difficulty ratings", icon: "" },
    { id: 477, name: "First Project Recommender", slug: "first-project", description: "Your first sewing project", icon: "" },
    { id: 478, name: "Pattern Reading Tutorial", slug: "pattern-reading", description: "How to read patterns", icon: "" },
    { id: 479, name: "Technique Library", slug: "technique-library", description: "Sewing technique index", icon: "" },
    { id: 480, name: "Pressing vs Ironing", slug: "pressing-guide", description: "Press vs iron guide", icon: "" },
    { id: 481, name: "Fabric Prep Guide", slug: "fabric-prep", description: "Pre-wash and prepare fabric", icon: "" },
    { id: 482, name: "Sewing Tool Guide", slug: "tool-guide", description: "Guide to all sewing tools", icon: "" },
    { id: 483, name: "Fitting Flowchart", slug: "fitting-flowchart", description: "Fix fitting problems", icon: "" },
    { id: 484, name: "Sewing Math Formulas", slug: "math-formulas", description: "All sewing math formulas", icon: "" },
];
